services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=sensors
      - POSTGRES_USER=sensors
      - POSTGRES_DB=sensors
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "sensors" ]
      timeout: 10s
      retries: 10

  main:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - DB_HOST=db
      - DB_USER=sensors
      - DB_PASSWORD=sensors
      - DB_NAME=sensors
      - DB_PORT=5432
      - ROOT_PATH=/
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
